#version: "3.7"
services:
  bitcoin-node-manager:
    container_name: bitcoin-node-manager
    image: php:8.2-apache
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "myapp" with your app name in the traefik labels
      # Main
      generated: true
      traefik.enable: true
      traefik.http.middlewares.bitcoin-node-manager-web-redirect.redirectscheme.scheme: https
      traefik.http.services.bitcoin-node-manager.loadbalancer.server.port: 80 # Should be the same as the app internal port so for this example 9443
      traefik.http.routers.bitcoin-node-manager-local-insecure.rule: Host(`bitcoin-node-manager.${LOCAL_DOMAIN}`)
      traefik.http.routers.bitcoin-node-manager-local-insecure.entrypoints: web
      traefik.http.routers.bitcoin-node-manager-local-insecure.service: bitcoin-node-manager
      traefik.http.routers.bitcoin-node-manager-local-insecure.middlewares: bitcoin-node-manager-web-redirect
      traefik.http.routers.bitcoin-node-manager-local.rule: Host(`bitcoin-node-manager.${LOCAL_DOMAIN}`)
      traefik.http.routers.bitcoin-node-manager-local.entrypoints: websecure
      traefik.http.routers.bitcoin-node-manager-local.service: bitcoin-node-manager
      traefik.http.routers.bitcoin-node-manager.tls: true
      runtipi.managed: true
    #user: 0:0
    #stop_grace_period: 15m30s
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

